all: main

main: main.c
	gcc -Wall main.c -o main
	
test:	
	./main /home/maciek/sysopy/LAB1/zad1 3000 normal

test2: main
	./main /home/maciek/sysopy/LAB2 3000 unftw

test3: main
	./main KAT1/ 3000 unftw

clean:
	rm -f *.a *.o *.so *.out
